# Generated by Django 5.0.4 on 2024-05-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0004_booking_bookingservice_guest_hotelcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('guest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_service.guest')),
                ('owner_exp_status', models.IntegerField(null=True)),
            ],
            bases=('booking_service.guest',),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('s', 'single'), ('d', 'double'), ('o', 'other')], max_length=1),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name'], name='last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['age'], name='age_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='stars_idx'),
        ),
    ]
