# Generated by Django 4.2.13 on 2024-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0008_alter_guest_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotels_photo/', verbose_name='photo'),
        ),
    ]
