# Generated by Django 4.2.13 on 2024-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0009_hotel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotels_photo/', verbose_name='hotel_photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photo/', verbose_name='user_photo'),
        ),
    ]
